version: 99.0.{build}
skip_tags: true
os: Visual Studio 2015
configuration: Release
install:
- ps: >-
    $null = md obj\tools

    Invoke-WebRequest https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1 -OutFile obj\tools\dotnet-install.ps1

    .\obj\tools\dotnet-install.ps1
build_script:
- ps: >-
    dotnet restore src

    dotnet pack src\PCLCommandBase -c Release
artifacts:
- path: src\**\*.nupkg
